"""add_connections_and_request_tracking

Revision ID: c0fc635ae432
Revises: ec9c6cb15b41
Create Date: 2026-01-05 12:28:34.602141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc635ae432'
down_revision: Union[str, Sequence[str], None] = 'ec9c6cb15b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiator_id', 'receiver_id', name='uq_connection_link')
    )
    op.create_index(op.f('ix_connections_request_id'), 'connections', ['request_id'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.add_column('agent_traces', sa.Column('target_id', sa.UUID(), nullable=True))
    op.add_column('agent_traces', sa.Column('request_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_agent_traces_request_id'), 'agent_traces', ['request_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_target_id'), 'agent_traces', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_traces_target_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_request_id'), table_name='agent_traces')
    op.drop_column('agent_traces', 'request_id')
    op.drop_column('agent_traces', 'target_id')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_request_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
