"""add_metadata_fields

Revision ID: ec9c6cb15b41
Revises: 437c526cca73
Create Date: 2025-12-31 11:32:54.977856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlalchemy.dialects.postgresql as psql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ec9c6cb15b41'
down_revision: Union[str, Sequence[str], None] = '437c526cca73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_location'), table_name='users')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'role')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
