global:
  scrape_interval: 5s
  evaluation_interval: 15s # How often to check the alert rules

# 1. Load the Rules
rule_files:
  - "alerts.rules.yml"

# 2. Talk to Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'qoneqt_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']