global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'qoneqt_api'
    metrics_path: '/metrics'
    static_configs:
      # 'app' is the docker service name. 
      # Since we are running uvicorn on host, use 'host.docker.internal'
      # If you move uvicorn to docker later, change this to 'app:8000'
      - targets: ['host.docker.internal:8080']